/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        tertiary: "#3a495f",
        surface: "#f8f9fa",
        "surface-tint": "#4d44e3",
        "inverse-primary": "#c3c0ff",
        "on-error": "#ffffff",
        primary: "#3525cd",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#4f46e5",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#e1e3e4",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-fixed": "#e2dfff",
        outline: "#777587",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#516177",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary-container": "#5c647a",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#3f465c",
        secondary: "#565e74",
        "on-primary-container": "#dad7ff",
        background: "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "secondary-container": "#dae2fd",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        "on-tertiary-container": "#ccdcf7",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#3323cc",
        "on-surface-variant": "#464555",
        "surface-container": "#edeeef",
        "on-secondary-fixed": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "card-gap": "20px",
        base: "4px",
        "section-margin": "40px",
        "container-padding": "24px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "mono-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "mono-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
